import {Header} from '@/components//Header';
import {Footer} from "@/components/Footer";
import Head from "next/head";
import {Lato} from 'next/font/google';
import "@/assets/styles/globals.css";

const lato = Lato({weight: ['400', '700'], subsets: ['latin']});

export const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css"/>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={lato.className}>
                <Header/>
                {children}
                <Footer/>
            </main>
        </>
    );
}