import Head from "next/head";
import {HeroSection} from "@/components/HeroSection";
import {Header} from "@/components/Header";
import {DoSection} from "@/components/DoSection";
import {ClientsSection} from "@/components/ClientsSection";
import {ProductsSection} from "@/components/ProductsSection";
import {NumeralsSection} from "@/components/NumeralsSection";
import {CareerSection} from "@/components/CareerSection";
import {AwardsSection} from "@/components/AwardsSection";
import {Footer} from "@/components/Footer";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css"/>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, user-scalable=no, shrink-to-fit=no"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Header/>
                <HeroSection/>
                <DoSection/>
                <ClientsSection/>
                <ProductsSection/>
                <NumeralsSection/>
                <AwardsSection/>
                <CareerSection/>
                <Footer/>
            </main>
        </>
    );
}